/*
 * Auth Service
 * This API provides token-based authentication for user registration, login, and client credential management. It ensures secure communication by utilizing tokens for authentication. Users can register with unique usernames and passwords, authenticate using client credentials, retrieve client IDs and secrets, and regenerate client credentials as needed. The API supports various user roles, including 'user', 'admin', 'moderator', 'guest', and 'superadmin'.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package authservice.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LoginClientPost200Response
 */
public class LoginClientPost200ResponseTest {
    private final LoginClientPost200Response model = new LoginClientPost200Response();

    /**
     * Model tests for LoginClientPost200Response
     */
    @Test
    public void testLoginClientPost200Response() {
        // TODO: test LoginClientPost200Response
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'tokenType'
     */
    @Test
    public void tokenTypeTest() {
        // TODO: test tokenType
    }

    /**
     * Test the property 'expiresIn'
     */
    @Test
    public void expiresInTest() {
        // TODO: test expiresIn
    }

}
