name: Publish Maven Package

on:
  release:

jobs:
  build:
    name: Build Reseller API
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'temurin'
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.SDK_TOKEN }}